# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Connector_Definition.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(440, 322)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.comboBox_connector = QtGui.QComboBox(Dialog)
        self.comboBox_connector.setObjectName(_fromUtf8("comboBox_connector"))
        self.horizontalLayout_2.addWidget(self.comboBox_connector)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_defineown = QtGui.QWidget()
        self.page_defineown.setObjectName(_fromUtf8("page_defineown"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_defineown)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.textBrowser = QtGui.QTextBrowser(self.page_defineown)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_3.addWidget(self.textBrowser)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.stackedWidget.addWidget(self.page_defineown)
        self.page_cata = QtGui.QWidget()
        self.page_cata.setObjectName(_fromUtf8("page_cata"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_cata)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(self.page_cata)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cata_rb_weights = QtGui.QRadioButton(self.page_cata)
        self.cata_rb_weights.setText(_fromUtf8(""))
        self.cata_rb_weights.setChecked(True)
        self.cata_rb_weights.setObjectName(_fromUtf8("cata_rb_weights"))
        self.buttonGroup = QtGui.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.cata_rb_weights)
        self.horizontalLayout_3.addWidget(self.cata_rb_weights)
        self.cata_weights = QtGui.QDoubleSpinBox(self.page_cata)
        self.cata_weights.setObjectName(_fromUtf8("cata_weights"))
        self.horizontalLayout_3.addWidget(self.cata_weights)
        self.cata_rb_weights2 = QtGui.QRadioButton(self.page_cata)
        self.cata_rb_weights2.setText(_fromUtf8(""))
        self.cata_rb_weights2.setObjectName(_fromUtf8("cata_rb_weights2"))
        self.buttonGroup.addButton(self.cata_rb_weights2)
        self.horizontalLayout_3.addWidget(self.cata_rb_weights2)
        self.label_48 = QtGui.QLabel(self.page_cata)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.horizontalLayout_3.addWidget(self.label_48)
        self.label_46 = QtGui.QLabel(self.page_cata)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_3.addWidget(self.label_46)
        self.cata_weights_min = QtGui.QDoubleSpinBox(self.page_cata)
        self.cata_weights_min.setEnabled(False)
        self.cata_weights_min.setObjectName(_fromUtf8("cata_weights_min"))
        self.horizontalLayout_3.addWidget(self.cata_weights_min)
        self.label_47 = QtGui.QLabel(self.page_cata)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_3.addWidget(self.label_47)
        self.cata_weights_max = QtGui.QDoubleSpinBox(self.page_cata)
        self.cata_weights_max.setEnabled(False)
        self.cata_weights_max.setObjectName(_fromUtf8("cata_weights_max"))
        self.horizontalLayout_3.addWidget(self.cata_weights_max)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.label_3 = QtGui.QLabel(self.page_cata)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cata_rb_delays = QtGui.QRadioButton(self.page_cata)
        self.cata_rb_delays.setText(_fromUtf8(""))
        self.cata_rb_delays.setChecked(True)
        self.cata_rb_delays.setObjectName(_fromUtf8("cata_rb_delays"))
        self.buttonGroup_2 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.cata_rb_delays)
        self.horizontalLayout_4.addWidget(self.cata_rb_delays)
        self.cata_delays = QtGui.QDoubleSpinBox(self.page_cata)
        self.cata_delays.setObjectName(_fromUtf8("cata_delays"))
        self.horizontalLayout_4.addWidget(self.cata_delays)
        self.cata_rb_delays2 = QtGui.QRadioButton(self.page_cata)
        self.cata_rb_delays2.setText(_fromUtf8(""))
        self.cata_rb_delays2.setObjectName(_fromUtf8("cata_rb_delays2"))
        self.buttonGroup_2.addButton(self.cata_rb_delays2)
        self.horizontalLayout_4.addWidget(self.cata_rb_delays2)
        self.label_49 = QtGui.QLabel(self.page_cata)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_4.addWidget(self.label_49)
        self.label_50 = QtGui.QLabel(self.page_cata)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_4.addWidget(self.label_50)
        self.cata_delays_min = QtGui.QDoubleSpinBox(self.page_cata)
        self.cata_delays_min.setEnabled(False)
        self.cata_delays_min.setObjectName(_fromUtf8("cata_delays_min"))
        self.horizontalLayout_4.addWidget(self.cata_delays_min)
        self.label_51 = QtGui.QLabel(self.page_cata)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.horizontalLayout_4.addWidget(self.label_51)
        self.cata_delays_max = QtGui.QDoubleSpinBox(self.page_cata)
        self.cata_delays_max.setEnabled(False)
        self.cata_delays_max.setObjectName(_fromUtf8("cata_delays_max"))
        self.horizontalLayout_4.addWidget(self.cata_delays_max)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_4 = QtGui.QLabel(self.page_cata)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_5.addWidget(self.label_4)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.cata_asc = QtGui.QCheckBox(self.page_cata)
        self.cata_asc.setText(_fromUtf8(""))
        self.cata_asc.setObjectName(_fromUtf8("cata_asc"))
        self.horizontalLayout_5.addWidget(self.cata_asc)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.page_cata)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.cata_fmw = QtGui.QCheckBox(self.page_cata)
        self.cata_fmw.setText(_fromUtf8(""))
        self.cata_fmw.setObjectName(_fromUtf8("cata_fmw"))
        self.horizontalLayout_6.addWidget(self.cata_fmw)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.page_cata)
        self.page_cd = QtGui.QWidget()
        self.page_cd.setObjectName(_fromUtf8("page_cd"))
        self.gridLayout = QtGui.QGridLayout(self.page_cd)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.page_cd)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cd_amp_pos = QtGui.QDoubleSpinBox(self.page_cd)
        self.cd_amp_pos.setObjectName(_fromUtf8("cd_amp_pos"))
        self.gridLayout.addWidget(self.cd_amp_pos, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 0, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.page_cd)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 4, 1, 1)
        self.cd_amp_neg = QtGui.QDoubleSpinBox(self.page_cd)
        self.cd_amp_neg.setObjectName(_fromUtf8("cd_amp_neg"))
        self.gridLayout.addWidget(self.cd_amp_neg, 0, 5, 1, 1)
        self.label_7 = QtGui.QLabel(self.page_cd)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.cd_sigma_pos = QtGui.QDoubleSpinBox(self.page_cd)
        self.cd_sigma_pos.setObjectName(_fromUtf8("cd_sigma_pos"))
        self.gridLayout.addWidget(self.cd_sigma_pos, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.page_cd)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 1, 4, 1, 1)
        self.cd_sigma_neg = QtGui.QDoubleSpinBox(self.page_cd)
        self.cd_sigma_neg.setObjectName(_fromUtf8("cd_sigma_neg"))
        self.gridLayout.addWidget(self.cd_sigma_neg, 1, 5, 1, 1)
        self.label_11 = QtGui.QLabel(self.page_cd)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 2)
        self.label_12 = QtGui.QLabel(self.page_cd)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 2, 4, 1, 1)
        self.cd_limit = QtGui.QDoubleSpinBox(self.page_cd)
        self.cd_limit.setProperty("value", 0.01)
        self.cd_limit.setObjectName(_fromUtf8("cd_limit"))
        self.gridLayout.addWidget(self.cd_limit, 2, 5, 1, 1)
        self.label_10 = QtGui.QLabel(self.page_cd)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.cd_rb_delays = QtGui.QRadioButton(self.page_cd)
        self.cd_rb_delays.setText(_fromUtf8(""))
        self.cd_rb_delays.setChecked(True)
        self.cd_rb_delays.setObjectName(_fromUtf8("cd_rb_delays"))
        self.buttonGroup_3 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_3.setObjectName(_fromUtf8("buttonGroup_3"))
        self.buttonGroup_3.addButton(self.cd_rb_delays)
        self.horizontalLayout_7.addWidget(self.cd_rb_delays)
        self.cd_delays = QtGui.QDoubleSpinBox(self.page_cd)
        self.cd_delays.setObjectName(_fromUtf8("cd_delays"))
        self.horizontalLayout_7.addWidget(self.cd_delays)
        self.cd_rb_delays2 = QtGui.QRadioButton(self.page_cd)
        self.cd_rb_delays2.setText(_fromUtf8(""))
        self.cd_rb_delays2.setObjectName(_fromUtf8("cd_rb_delays2"))
        self.buttonGroup_3.addButton(self.cd_rb_delays2)
        self.horizontalLayout_7.addWidget(self.cd_rb_delays2)
        self.label_52 = QtGui.QLabel(self.page_cd)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.horizontalLayout_7.addWidget(self.label_52)
        self.label_53 = QtGui.QLabel(self.page_cd)
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.horizontalLayout_7.addWidget(self.label_53)
        self.cd_delays_min = QtGui.QDoubleSpinBox(self.page_cd)
        self.cd_delays_min.setEnabled(False)
        self.cd_delays_min.setObjectName(_fromUtf8("cd_delays_min"))
        self.horizontalLayout_7.addWidget(self.cd_delays_min)
        self.label_54 = QtGui.QLabel(self.page_cd)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.horizontalLayout_7.addWidget(self.label_54)
        self.cd_delays_max = QtGui.QDoubleSpinBox(self.page_cd)
        self.cd_delays_max.setEnabled(False)
        self.cd_delays_max.setObjectName(_fromUtf8("cd_delays_max"))
        self.horizontalLayout_7.addWidget(self.cd_delays_max)
        self.gridLayout.addLayout(self.horizontalLayout_7, 4, 0, 1, 6)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem7, 5, 4, 1, 1)
        self.cd_asc = QtGui.QCheckBox(self.page_cd)
        self.cd_asc.setText(_fromUtf8(""))
        self.cd_asc.setObjectName(_fromUtf8("cd_asc"))
        self.gridLayout.addWidget(self.cd_asc, 2, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_cd)
        self.page_cfn_post = QtGui.QWidget()
        self.page_cfn_post.setObjectName(_fromUtf8("page_cfn_post"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_cfn_post)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_14 = QtGui.QLabel(self.page_cfn_post)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.cfn_post_rb_weights = QtGui.QRadioButton(self.page_cfn_post)
        self.cfn_post_rb_weights.setText(_fromUtf8(""))
        self.cfn_post_rb_weights.setChecked(True)
        self.cfn_post_rb_weights.setObjectName(_fromUtf8("cfn_post_rb_weights"))
        self.buttonGroup_4 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_4.setObjectName(_fromUtf8("buttonGroup_4"))
        self.buttonGroup_4.addButton(self.cfn_post_rb_weights)
        self.horizontalLayout_9.addWidget(self.cfn_post_rb_weights)
        self.cfn_post_weights = QtGui.QDoubleSpinBox(self.page_cfn_post)
        self.cfn_post_weights.setObjectName(_fromUtf8("cfn_post_weights"))
        self.horizontalLayout_9.addWidget(self.cfn_post_weights)
        self.cfn_post_rb_weights2 = QtGui.QRadioButton(self.page_cfn_post)
        self.cfn_post_rb_weights2.setText(_fromUtf8(""))
        self.cfn_post_rb_weights2.setObjectName(_fromUtf8("cfn_post_rb_weights2"))
        self.buttonGroup_4.addButton(self.cfn_post_rb_weights2)
        self.horizontalLayout_9.addWidget(self.cfn_post_rb_weights2)
        self.label_58 = QtGui.QLabel(self.page_cfn_post)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.horizontalLayout_9.addWidget(self.label_58)
        self.label_59 = QtGui.QLabel(self.page_cfn_post)
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.horizontalLayout_9.addWidget(self.label_59)
        self.cfn_post_weights_min = QtGui.QDoubleSpinBox(self.page_cfn_post)
        self.cfn_post_weights_min.setEnabled(False)
        self.cfn_post_weights_min.setObjectName(_fromUtf8("cfn_post_weights_min"))
        self.horizontalLayout_9.addWidget(self.cfn_post_weights_min)
        self.label_60 = QtGui.QLabel(self.page_cfn_post)
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.horizontalLayout_9.addWidget(self.label_60)
        self.cfn_post_weights_max = QtGui.QDoubleSpinBox(self.page_cfn_post)
        self.cfn_post_weights_max.setEnabled(False)
        self.cfn_post_weights_max.setObjectName(_fromUtf8("cfn_post_weights_max"))
        self.horizontalLayout_9.addWidget(self.cfn_post_weights_max)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 1, 0, 1, 4)
        self.label_15 = QtGui.QLabel(self.page_cfn_post)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.cfn_post_rb_delays = QtGui.QRadioButton(self.page_cfn_post)
        self.cfn_post_rb_delays.setText(_fromUtf8(""))
        self.cfn_post_rb_delays.setChecked(True)
        self.cfn_post_rb_delays.setObjectName(_fromUtf8("cfn_post_rb_delays"))
        self.buttonGroup_5 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_5.setObjectName(_fromUtf8("buttonGroup_5"))
        self.buttonGroup_5.addButton(self.cfn_post_rb_delays)
        self.horizontalLayout_8.addWidget(self.cfn_post_rb_delays)
        self.cfn_post_delays = QtGui.QDoubleSpinBox(self.page_cfn_post)
        self.cfn_post_delays.setObjectName(_fromUtf8("cfn_post_delays"))
        self.horizontalLayout_8.addWidget(self.cfn_post_delays)
        self.cfn_post_rb_delays2 = QtGui.QRadioButton(self.page_cfn_post)
        self.cfn_post_rb_delays2.setText(_fromUtf8(""))
        self.cfn_post_rb_delays2.setObjectName(_fromUtf8("cfn_post_rb_delays2"))
        self.buttonGroup_5.addButton(self.cfn_post_rb_delays2)
        self.horizontalLayout_8.addWidget(self.cfn_post_rb_delays2)
        self.label_55 = QtGui.QLabel(self.page_cfn_post)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.horizontalLayout_8.addWidget(self.label_55)
        self.label_56 = QtGui.QLabel(self.page_cfn_post)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.horizontalLayout_8.addWidget(self.label_56)
        self.cfn_post_delays_min = QtGui.QDoubleSpinBox(self.page_cfn_post)
        self.cfn_post_delays_min.setEnabled(False)
        self.cfn_post_delays_min.setObjectName(_fromUtf8("cfn_post_delays_min"))
        self.horizontalLayout_8.addWidget(self.cfn_post_delays_min)
        self.label_57 = QtGui.QLabel(self.page_cfn_post)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.horizontalLayout_8.addWidget(self.label_57)
        self.cfn_post_delays_max = QtGui.QDoubleSpinBox(self.page_cfn_post)
        self.cfn_post_delays_max.setEnabled(False)
        self.cfn_post_delays_max.setObjectName(_fromUtf8("cfn_post_delays_max"))
        self.horizontalLayout_8.addWidget(self.cfn_post_delays_max)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 3, 0, 1, 4)
        self.label_13 = QtGui.QLabel(self.page_cfn_post)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(199, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 4, 2, 1, 1)
        self.cfn_post_number = QtGui.QSpinBox(self.page_cfn_post)
        self.cfn_post_number.setMaximum(99999)
        self.cfn_post_number.setObjectName(_fromUtf8("cfn_post_number"))
        self.gridLayout_2.addWidget(self.cfn_post_number, 4, 3, 1, 1)
        self.label_16 = QtGui.QLabel(self.page_cfn_post)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 5, 0, 1, 2)
        self.cfn_post_asc = QtGui.QCheckBox(self.page_cfn_post)
        self.cfn_post_asc.setText(_fromUtf8(""))
        self.cfn_post_asc.setObjectName(_fromUtf8("cfn_post_asc"))
        self.gridLayout_2.addWidget(self.cfn_post_asc, 5, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.page_cfn_post)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 6, 0, 1, 2)
        self.cfn_post_fmw = QtGui.QCheckBox(self.page_cfn_post)
        self.cfn_post_fmw.setText(_fromUtf8(""))
        self.cfn_post_fmw.setObjectName(_fromUtf8("cfn_post_fmw"))
        self.gridLayout_2.addWidget(self.cfn_post_fmw, 6, 3, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem9, 7, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_cfn_post)
        self.page_cfn_pre = QtGui.QWidget()
        self.page_cfn_pre.setObjectName(_fromUtf8("page_cfn_pre"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_cfn_pre)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_20 = QtGui.QLabel(self.page_cfn_pre)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.cfn_pre_rb_weights = QtGui.QRadioButton(self.page_cfn_pre)
        self.cfn_pre_rb_weights.setText(_fromUtf8(""))
        self.cfn_pre_rb_weights.setChecked(True)
        self.cfn_pre_rb_weights.setObjectName(_fromUtf8("cfn_pre_rb_weights"))
        self.buttonGroup_6 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_6.setObjectName(_fromUtf8("buttonGroup_6"))
        self.buttonGroup_6.addButton(self.cfn_pre_rb_weights)
        self.horizontalLayout_10.addWidget(self.cfn_pre_rb_weights)
        self.cfn_pre_weights = QtGui.QDoubleSpinBox(self.page_cfn_pre)
        self.cfn_pre_weights.setObjectName(_fromUtf8("cfn_pre_weights"))
        self.horizontalLayout_10.addWidget(self.cfn_pre_weights)
        self.cfn_pre_rb_weights2 = QtGui.QRadioButton(self.page_cfn_pre)
        self.cfn_pre_rb_weights2.setText(_fromUtf8(""))
        self.cfn_pre_rb_weights2.setObjectName(_fromUtf8("cfn_pre_rb_weights2"))
        self.buttonGroup_6.addButton(self.cfn_pre_rb_weights2)
        self.horizontalLayout_10.addWidget(self.cfn_pre_rb_weights2)
        self.label_61 = QtGui.QLabel(self.page_cfn_pre)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.horizontalLayout_10.addWidget(self.label_61)
        self.label_62 = QtGui.QLabel(self.page_cfn_pre)
        self.label_62.setObjectName(_fromUtf8("label_62"))
        self.horizontalLayout_10.addWidget(self.label_62)
        self.cfn_pre_weights_min = QtGui.QDoubleSpinBox(self.page_cfn_pre)
        self.cfn_pre_weights_min.setEnabled(False)
        self.cfn_pre_weights_min.setObjectName(_fromUtf8("cfn_pre_weights_min"))
        self.horizontalLayout_10.addWidget(self.cfn_pre_weights_min)
        self.label_63 = QtGui.QLabel(self.page_cfn_pre)
        self.label_63.setObjectName(_fromUtf8("label_63"))
        self.horizontalLayout_10.addWidget(self.label_63)
        self.cfn_pre_weights_max = QtGui.QDoubleSpinBox(self.page_cfn_pre)
        self.cfn_pre_weights_max.setEnabled(False)
        self.cfn_pre_weights_max.setObjectName(_fromUtf8("cfn_pre_weights_max"))
        self.horizontalLayout_10.addWidget(self.cfn_pre_weights_max)
        self.gridLayout_3.addLayout(self.horizontalLayout_10, 1, 0, 1, 4)
        self.label_19 = QtGui.QLabel(self.page_cfn_pre)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.cfn_pre_rb_delays = QtGui.QRadioButton(self.page_cfn_pre)
        self.cfn_pre_rb_delays.setText(_fromUtf8(""))
        self.cfn_pre_rb_delays.setChecked(True)
        self.cfn_pre_rb_delays.setObjectName(_fromUtf8("cfn_pre_rb_delays"))
        self.buttonGroup_7 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_7.setObjectName(_fromUtf8("buttonGroup_7"))
        self.buttonGroup_7.addButton(self.cfn_pre_rb_delays)
        self.horizontalLayout_11.addWidget(self.cfn_pre_rb_delays)
        self.cfn_pre_delays = QtGui.QDoubleSpinBox(self.page_cfn_pre)
        self.cfn_pre_delays.setObjectName(_fromUtf8("cfn_pre_delays"))
        self.horizontalLayout_11.addWidget(self.cfn_pre_delays)
        self.cfn_pre_rb_delays2 = QtGui.QRadioButton(self.page_cfn_pre)
        self.cfn_pre_rb_delays2.setText(_fromUtf8(""))
        self.cfn_pre_rb_delays2.setObjectName(_fromUtf8("cfn_pre_rb_delays2"))
        self.buttonGroup_7.addButton(self.cfn_pre_rb_delays2)
        self.horizontalLayout_11.addWidget(self.cfn_pre_rb_delays2)
        self.label_64 = QtGui.QLabel(self.page_cfn_pre)
        self.label_64.setObjectName(_fromUtf8("label_64"))
        self.horizontalLayout_11.addWidget(self.label_64)
        self.label_65 = QtGui.QLabel(self.page_cfn_pre)
        self.label_65.setObjectName(_fromUtf8("label_65"))
        self.horizontalLayout_11.addWidget(self.label_65)
        self.cfn_pre_delays_min = QtGui.QDoubleSpinBox(self.page_cfn_pre)
        self.cfn_pre_delays_min.setEnabled(False)
        self.cfn_pre_delays_min.setObjectName(_fromUtf8("cfn_pre_delays_min"))
        self.horizontalLayout_11.addWidget(self.cfn_pre_delays_min)
        self.label_66 = QtGui.QLabel(self.page_cfn_pre)
        self.label_66.setObjectName(_fromUtf8("label_66"))
        self.horizontalLayout_11.addWidget(self.label_66)
        self.cfn_pre_delays_max = QtGui.QDoubleSpinBox(self.page_cfn_pre)
        self.cfn_pre_delays_max.setEnabled(False)
        self.cfn_pre_delays_max.setObjectName(_fromUtf8("cfn_pre_delays_max"))
        self.horizontalLayout_11.addWidget(self.cfn_pre_delays_max)
        self.gridLayout_3.addLayout(self.horizontalLayout_11, 3, 0, 1, 4)
        self.label_22 = QtGui.QLabel(self.page_cfn_pre)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 4, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(199, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 4, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.page_cfn_pre)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 5, 0, 1, 2)
        self.cfn_pre_asc = QtGui.QCheckBox(self.page_cfn_pre)
        self.cfn_pre_asc.setText(_fromUtf8(""))
        self.cfn_pre_asc.setObjectName(_fromUtf8("cfn_pre_asc"))
        self.gridLayout_3.addWidget(self.cfn_pre_asc, 5, 3, 1, 1)
        self.label_21 = QtGui.QLabel(self.page_cfn_pre)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 6, 0, 1, 2)
        self.cfn_pre_fmw = QtGui.QCheckBox(self.page_cfn_pre)
        self.cfn_pre_fmw.setText(_fromUtf8(""))
        self.cfn_pre_fmw.setObjectName(_fromUtf8("cfn_pre_fmw"))
        self.gridLayout_3.addWidget(self.cfn_pre_fmw, 6, 3, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(20, 15, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 7, 1, 1, 1)
        self.cfn_pre_number = QtGui.QSpinBox(self.page_cfn_pre)
        self.cfn_pre_number.setMaximum(99999)
        self.cfn_pre_number.setObjectName(_fromUtf8("cfn_pre_number"))
        self.gridLayout_3.addWidget(self.cfn_pre_number, 4, 3, 1, 1)
        self.stackedWidget.addWidget(self.page_cfn_pre)
        self.page_cfp = QtGui.QWidget()
        self.page_cfp.setObjectName(_fromUtf8("page_cfp"))
        self.gridLayout_4 = QtGui.QGridLayout(self.page_cfp)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_24 = QtGui.QLabel(self.page_cfp)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.cfp_rb_weights = QtGui.QRadioButton(self.page_cfp)
        self.cfp_rb_weights.setText(_fromUtf8(""))
        self.cfp_rb_weights.setChecked(True)
        self.cfp_rb_weights.setObjectName(_fromUtf8("cfp_rb_weights"))
        self.buttonGroup_8 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_8.setObjectName(_fromUtf8("buttonGroup_8"))
        self.buttonGroup_8.addButton(self.cfp_rb_weights)
        self.horizontalLayout_12.addWidget(self.cfp_rb_weights)
        self.cfp_weights = QtGui.QDoubleSpinBox(self.page_cfp)
        self.cfp_weights.setObjectName(_fromUtf8("cfp_weights"))
        self.horizontalLayout_12.addWidget(self.cfp_weights)
        self.cfp_rb_weights2 = QtGui.QRadioButton(self.page_cfp)
        self.cfp_rb_weights2.setText(_fromUtf8(""))
        self.cfp_rb_weights2.setObjectName(_fromUtf8("cfp_rb_weights2"))
        self.buttonGroup_8.addButton(self.cfp_rb_weights2)
        self.horizontalLayout_12.addWidget(self.cfp_rb_weights2)
        self.label_67 = QtGui.QLabel(self.page_cfp)
        self.label_67.setObjectName(_fromUtf8("label_67"))
        self.horizontalLayout_12.addWidget(self.label_67)
        self.label_68 = QtGui.QLabel(self.page_cfp)
        self.label_68.setObjectName(_fromUtf8("label_68"))
        self.horizontalLayout_12.addWidget(self.label_68)
        self.cfp_weights_min = QtGui.QDoubleSpinBox(self.page_cfp)
        self.cfp_weights_min.setEnabled(False)
        self.cfp_weights_min.setObjectName(_fromUtf8("cfp_weights_min"))
        self.horizontalLayout_12.addWidget(self.cfp_weights_min)
        self.label_69 = QtGui.QLabel(self.page_cfp)
        self.label_69.setObjectName(_fromUtf8("label_69"))
        self.horizontalLayout_12.addWidget(self.label_69)
        self.cfp_weights_max = QtGui.QDoubleSpinBox(self.page_cfp)
        self.cfp_weights_max.setEnabled(False)
        self.cfp_weights_max.setObjectName(_fromUtf8("cfp_weights_max"))
        self.horizontalLayout_12.addWidget(self.cfp_weights_max)
        self.gridLayout_4.addLayout(self.horizontalLayout_12, 1, 0, 1, 4)
        self.label_23 = QtGui.QLabel(self.page_cfp)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 2, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem12, 4, 1, 1, 1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.cfp_rb_delays = QtGui.QRadioButton(self.page_cfp)
        self.cfp_rb_delays.setText(_fromUtf8(""))
        self.cfp_rb_delays.setChecked(True)
        self.cfp_rb_delays.setObjectName(_fromUtf8("cfp_rb_delays"))
        self.buttonGroup_9 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_9.setObjectName(_fromUtf8("buttonGroup_9"))
        self.buttonGroup_9.addButton(self.cfp_rb_delays)
        self.horizontalLayout_13.addWidget(self.cfp_rb_delays)
        self.cfp_delays = QtGui.QDoubleSpinBox(self.page_cfp)
        self.cfp_delays.setObjectName(_fromUtf8("cfp_delays"))
        self.horizontalLayout_13.addWidget(self.cfp_delays)
        self.cfp_rb_delays2 = QtGui.QRadioButton(self.page_cfp)
        self.cfp_rb_delays2.setText(_fromUtf8(""))
        self.cfp_rb_delays2.setObjectName(_fromUtf8("cfp_rb_delays2"))
        self.buttonGroup_9.addButton(self.cfp_rb_delays2)
        self.horizontalLayout_13.addWidget(self.cfp_rb_delays2)
        self.label_70 = QtGui.QLabel(self.page_cfp)
        self.label_70.setObjectName(_fromUtf8("label_70"))
        self.horizontalLayout_13.addWidget(self.label_70)
        self.label_71 = QtGui.QLabel(self.page_cfp)
        self.label_71.setObjectName(_fromUtf8("label_71"))
        self.horizontalLayout_13.addWidget(self.label_71)
        self.cfp_delays_min = QtGui.QDoubleSpinBox(self.page_cfp)
        self.cfp_delays_min.setEnabled(False)
        self.cfp_delays_min.setObjectName(_fromUtf8("cfp_delays_min"))
        self.horizontalLayout_13.addWidget(self.cfp_delays_min)
        self.label_72 = QtGui.QLabel(self.page_cfp)
        self.label_72.setObjectName(_fromUtf8("label_72"))
        self.horizontalLayout_13.addWidget(self.label_72)
        self.cfp_delays_max = QtGui.QDoubleSpinBox(self.page_cfp)
        self.cfp_delays_max.setEnabled(False)
        self.cfp_delays_max.setObjectName(_fromUtf8("cfp_delays_max"))
        self.horizontalLayout_13.addWidget(self.cfp_delays_max)
        self.gridLayout_4.addLayout(self.horizontalLayout_13, 3, 0, 1, 4)
        self.label_27 = QtGui.QLabel(self.page_cfp)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 4, 0, 1, 1)
        self.label_26 = QtGui.QLabel(self.page_cfp)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 5, 0, 1, 1)
        self.cfp_asc = QtGui.QCheckBox(self.page_cfp)
        self.cfp_asc.setText(_fromUtf8(""))
        self.cfp_asc.setObjectName(_fromUtf8("cfp_asc"))
        self.gridLayout_4.addWidget(self.cfp_asc, 5, 3, 1, 1)
        self.label_25 = QtGui.QLabel(self.page_cfp)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 6, 0, 1, 1)
        self.cfp_fmw = QtGui.QCheckBox(self.page_cfp)
        self.cfp_fmw.setText(_fromUtf8(""))
        self.cfp_fmw.setObjectName(_fromUtf8("cfp_fmw"))
        self.gridLayout_4.addWidget(self.cfp_fmw, 6, 3, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem13, 7, 3, 1, 1)
        self.cfp_probability = QtGui.QDoubleSpinBox(self.page_cfp)
        self.cfp_probability.setMaximum(1.0)
        self.cfp_probability.setSingleStep(0.01)
        self.cfp_probability.setObjectName(_fromUtf8("cfp_probability"))
        self.gridLayout_4.addWidget(self.cfp_probability, 4, 2, 1, 1)
        self.label_73 = QtGui.QLabel(self.page_cfp)
        self.label_73.setObjectName(_fromUtf8("label_73"))
        self.gridLayout_4.addWidget(self.label_73, 4, 3, 1, 1)
        self.stackedWidget.addWidget(self.page_cfp)
        self.page_cff = QtGui.QWidget()
        self.page_cff.setObjectName(_fromUtf8("page_cff"))
        self.formLayout = QtGui.QFormLayout(self.page_cff)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cff_openfile = QtGui.QPushButton(self.page_cff)
        self.cff_openfile.setObjectName(_fromUtf8("cff_openfile"))
        self.horizontalLayout.addWidget(self.cff_openfile)
        self.label_43 = QtGui.QLabel(self.page_cff)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout.addWidget(self.label_43)
        self.cff_filename = QtGui.QLineEdit(self.page_cff)
        self.cff_filename.setAlignment(QtCore.Qt.AlignCenter)
        self.cff_filename.setReadOnly(True)
        self.cff_filename.setObjectName(_fromUtf8("cff_filename"))
        self.horizontalLayout.addWidget(self.cff_filename)
        self.formLayout.setLayout(0, QtGui.QFormLayout.SpanningRole, self.horizontalLayout)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout.setItem(1, QtGui.QFormLayout.LabelRole, spacerItem14)
        self.label_45 = QtGui.QLabel(self.page_cff)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_45)
        self.cff_filepath = QtGui.QPlainTextEdit(self.page_cff)
        self.cff_filepath.setFrameShape(QtGui.QFrame.StyledPanel)
        self.cff_filepath.setReadOnly(True)
        self.cff_filepath.setObjectName(_fromUtf8("cff_filepath"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.cff_filepath)
        self.stackedWidget.addWidget(self.page_cff)
        self.page_cfm = QtGui.QWidget()
        self.page_cfm.setObjectName(_fromUtf8("page_cfm"))
        self.formLayout_2 = QtGui.QFormLayout(self.page_cfm)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_28 = QtGui.QLabel(self.page_cfm)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_28)
        self.cfm_weights = QtGui.QPlainTextEdit(self.page_cfm)
        self.cfm_weights.setObjectName(_fromUtf8("cfm_weights"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.cfm_weights)
        self.label_29 = QtGui.QLabel(self.page_cfm)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_29)
        self.cfm_delays = QtGui.QTextEdit(self.page_cfm)
        self.cfm_delays.setObjectName(_fromUtf8("cfm_delays"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.cfm_delays)
        self.label_30 = QtGui.QLabel(self.page_cfm)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_30)
        self.cfm_pre_post = QtGui.QCheckBox(self.page_cfm)
        self.cfm_pre_post.setText(_fromUtf8(""))
        self.cfm_pre_post.setObjectName(_fromUtf8("cfm_pre_post"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.cfm_pre_post)
        self.stackedWidget.addWidget(self.page_cfm)
        self.page_cfs = QtGui.QWidget()
        self.page_cfs.setObjectName(_fromUtf8("page_cfs"))
        self.formLayout_7 = QtGui.QFormLayout(self.page_cfs)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_31 = QtGui.QLabel(self.page_cfs)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_31)
        self.cfs_weights = QtGui.QPlainTextEdit(self.page_cfs)
        self.cfs_weights.setObjectName(_fromUtf8("cfs_weights"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.cfs_weights)
        self.label_32 = QtGui.QLabel(self.page_cfs)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_32)
        self.cfs_delays = QtGui.QDoubleSpinBox(self.page_cfs)
        self.cfs_delays.setObjectName(_fromUtf8("cfs_delays"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.cfs_delays)
        self.stackedWidget.addWidget(self.page_cfs)
        self.page_cg = QtGui.QWidget()
        self.page_cg.setObjectName(_fromUtf8("page_cg"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_cg)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.cg_amp = QtGui.QDoubleSpinBox(self.page_cg)
        self.cg_amp.setObjectName(_fromUtf8("cg_amp"))
        self.gridLayout_5.addWidget(self.cg_amp, 0, 1, 1, 1)
        self.label_33 = QtGui.QLabel(self.page_cg)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_5.addWidget(self.label_33, 0, 0, 1, 1)
        self.label_35 = QtGui.QLabel(self.page_cg)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_5.addWidget(self.label_35, 2, 0, 1, 1)
        self.label_36 = QtGui.QLabel(self.page_cg)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_5.addWidget(self.label_36, 0, 4, 1, 1)
        self.cg_asc = QtGui.QCheckBox(self.page_cg)
        self.cg_asc.setText(_fromUtf8(""))
        self.cg_asc.setObjectName(_fromUtf8("cg_asc"))
        self.gridLayout_5.addWidget(self.cg_asc, 5, 5, 1, 1)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.cg_rb_delays = QtGui.QRadioButton(self.page_cg)
        self.cg_rb_delays.setText(_fromUtf8(""))
        self.cg_rb_delays.setChecked(True)
        self.cg_rb_delays.setObjectName(_fromUtf8("cg_rb_delays"))
        self.buttonGroup_10 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_10.setObjectName(_fromUtf8("buttonGroup_10"))
        self.buttonGroup_10.addButton(self.cg_rb_delays)
        self.horizontalLayout_14.addWidget(self.cg_rb_delays)
        self.cg_delays = QtGui.QDoubleSpinBox(self.page_cg)
        self.cg_delays.setObjectName(_fromUtf8("cg_delays"))
        self.horizontalLayout_14.addWidget(self.cg_delays)
        self.cg_rb_delays2 = QtGui.QRadioButton(self.page_cg)
        self.cg_rb_delays2.setText(_fromUtf8(""))
        self.cg_rb_delays2.setObjectName(_fromUtf8("cg_rb_delays2"))
        self.buttonGroup_10.addButton(self.cg_rb_delays2)
        self.horizontalLayout_14.addWidget(self.cg_rb_delays2)
        self.label_74 = QtGui.QLabel(self.page_cg)
        self.label_74.setObjectName(_fromUtf8("label_74"))
        self.horizontalLayout_14.addWidget(self.label_74)
        self.label_75 = QtGui.QLabel(self.page_cg)
        self.label_75.setObjectName(_fromUtf8("label_75"))
        self.horizontalLayout_14.addWidget(self.label_75)
        self.cg_delays_min = QtGui.QDoubleSpinBox(self.page_cg)
        self.cg_delays_min.setEnabled(False)
        self.cg_delays_min.setObjectName(_fromUtf8("cg_delays_min"))
        self.horizontalLayout_14.addWidget(self.cg_delays_min)
        self.label_76 = QtGui.QLabel(self.page_cg)
        self.label_76.setObjectName(_fromUtf8("label_76"))
        self.horizontalLayout_14.addWidget(self.label_76)
        self.cg_delays_max = QtGui.QDoubleSpinBox(self.page_cg)
        self.cg_delays_max.setEnabled(False)
        self.cg_delays_max.setObjectName(_fromUtf8("cg_delays_max"))
        self.horizontalLayout_14.addWidget(self.cg_delays_max)
        self.gridLayout_5.addLayout(self.horizontalLayout_14, 3, 0, 1, 6)
        self.label_34 = QtGui.QLabel(self.page_cg)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_5.addWidget(self.label_34, 0, 2, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem15, 1, 0, 1, 1)
        self.label_37 = QtGui.QLabel(self.page_cg)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_5.addWidget(self.label_37, 5, 0, 1, 2)
        self.cg_sigma = QtGui.QDoubleSpinBox(self.page_cg)
        self.cg_sigma.setObjectName(_fromUtf8("cg_sigma"))
        self.gridLayout_5.addWidget(self.cg_sigma, 0, 3, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem16, 6, 0, 1, 1)
        self.cg_limit = QtGui.QDoubleSpinBox(self.page_cg)
        self.cg_limit.setSingleStep(0.01)
        self.cg_limit.setObjectName(_fromUtf8("cg_limit"))
        self.gridLayout_5.addWidget(self.cg_limit, 0, 5, 1, 1)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem17, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_cg)
        self.page_coto = QtGui.QWidget()
        self.page_coto.setObjectName(_fromUtf8("page_coto"))
        self.gridLayout_6 = QtGui.QGridLayout(self.page_coto)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_41 = QtGui.QLabel(self.page_coto)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_6.addWidget(self.label_41, 6, 0, 1, 1)
        self.coto_fmw = QtGui.QCheckBox(self.page_coto)
        self.coto_fmw.setText(_fromUtf8(""))
        self.coto_fmw.setObjectName(_fromUtf8("coto_fmw"))
        self.gridLayout_6.addWidget(self.coto_fmw, 6, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.page_coto)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_6.addWidget(self.label_39, 2, 0, 1, 1)
        self.coto_shift = QtGui.QCheckBox(self.page_coto)
        self.coto_shift.setText(_fromUtf8(""))
        self.coto_shift.setObjectName(_fromUtf8("coto_shift"))
        self.gridLayout_6.addWidget(self.coto_shift, 5, 1, 1, 1)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.coto_rb_delays = QtGui.QRadioButton(self.page_coto)
        self.coto_rb_delays.setText(_fromUtf8(""))
        self.coto_rb_delays.setChecked(True)
        self.coto_rb_delays.setObjectName(_fromUtf8("coto_rb_delays"))
        self.buttonGroup_12 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_12.setObjectName(_fromUtf8("buttonGroup_12"))
        self.buttonGroup_12.addButton(self.coto_rb_delays)
        self.horizontalLayout_15.addWidget(self.coto_rb_delays)
        self.coto_delays = QtGui.QDoubleSpinBox(self.page_coto)
        self.coto_delays.setObjectName(_fromUtf8("coto_delays"))
        self.horizontalLayout_15.addWidget(self.coto_delays)
        self.coto_rb_delays2 = QtGui.QRadioButton(self.page_coto)
        self.coto_rb_delays2.setText(_fromUtf8(""))
        self.coto_rb_delays2.setObjectName(_fromUtf8("coto_rb_delays2"))
        self.buttonGroup_12.addButton(self.coto_rb_delays2)
        self.horizontalLayout_15.addWidget(self.coto_rb_delays2)
        self.label_77 = QtGui.QLabel(self.page_coto)
        self.label_77.setObjectName(_fromUtf8("label_77"))
        self.horizontalLayout_15.addWidget(self.label_77)
        self.label_78 = QtGui.QLabel(self.page_coto)
        self.label_78.setObjectName(_fromUtf8("label_78"))
        self.horizontalLayout_15.addWidget(self.label_78)
        self.coto_delays_min = QtGui.QDoubleSpinBox(self.page_coto)
        self.coto_delays_min.setEnabled(False)
        self.coto_delays_min.setObjectName(_fromUtf8("coto_delays_min"))
        self.horizontalLayout_15.addWidget(self.coto_delays_min)
        self.label_79 = QtGui.QLabel(self.page_coto)
        self.label_79.setObjectName(_fromUtf8("label_79"))
        self.horizontalLayout_15.addWidget(self.label_79)
        self.coto_delays_max = QtGui.QDoubleSpinBox(self.page_coto)
        self.coto_delays_max.setEnabled(False)
        self.coto_delays_max.setObjectName(_fromUtf8("coto_delays_max"))
        self.horizontalLayout_15.addWidget(self.coto_delays_max)
        self.gridLayout_6.addLayout(self.horizontalLayout_15, 3, 0, 1, 2)
        self.label_40 = QtGui.QLabel(self.page_coto)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_6.addWidget(self.label_40, 5, 0, 1, 1)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.coto_rb_weights = QtGui.QRadioButton(self.page_coto)
        self.coto_rb_weights.setText(_fromUtf8(""))
        self.coto_rb_weights.setChecked(True)
        self.coto_rb_weights.setObjectName(_fromUtf8("coto_rb_weights"))
        self.buttonGroup_11 = QtGui.QButtonGroup(Dialog)
        self.buttonGroup_11.setObjectName(_fromUtf8("buttonGroup_11"))
        self.buttonGroup_11.addButton(self.coto_rb_weights)
        self.horizontalLayout_16.addWidget(self.coto_rb_weights)
        self.coto_weights = QtGui.QDoubleSpinBox(self.page_coto)
        self.coto_weights.setObjectName(_fromUtf8("coto_weights"))
        self.horizontalLayout_16.addWidget(self.coto_weights)
        self.coto_rb_weights2 = QtGui.QRadioButton(self.page_coto)
        self.coto_rb_weights2.setText(_fromUtf8(""))
        self.coto_rb_weights2.setObjectName(_fromUtf8("coto_rb_weights2"))
        self.buttonGroup_11.addButton(self.coto_rb_weights2)
        self.horizontalLayout_16.addWidget(self.coto_rb_weights2)
        self.label_80 = QtGui.QLabel(self.page_coto)
        self.label_80.setObjectName(_fromUtf8("label_80"))
        self.horizontalLayout_16.addWidget(self.label_80)
        self.label_81 = QtGui.QLabel(self.page_coto)
        self.label_81.setObjectName(_fromUtf8("label_81"))
        self.horizontalLayout_16.addWidget(self.label_81)
        self.coto_weights_min = QtGui.QDoubleSpinBox(self.page_coto)
        self.coto_weights_min.setEnabled(False)
        self.coto_weights_min.setObjectName(_fromUtf8("coto_weights_min"))
        self.horizontalLayout_16.addWidget(self.coto_weights_min)
        self.label_82 = QtGui.QLabel(self.page_coto)
        self.label_82.setObjectName(_fromUtf8("label_82"))
        self.horizontalLayout_16.addWidget(self.label_82)
        self.coto_weights_max = QtGui.QDoubleSpinBox(self.page_coto)
        self.coto_weights_max.setEnabled(False)
        self.coto_weights_max.setObjectName(_fromUtf8("coto_weights_max"))
        self.horizontalLayout_16.addWidget(self.coto_weights_max)
        self.gridLayout_6.addLayout(self.horizontalLayout_16, 1, 0, 1, 2)
        self.label_38 = QtGui.QLabel(self.page_coto)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_6.addWidget(self.label_38, 0, 0, 1, 1)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem18, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_coto)
        self.page_cwf = QtGui.QWidget()
        self.page_cwf.setObjectName(_fromUtf8("page_cwf"))
        self.formLayout_10 = QtGui.QFormLayout(self.page_cwf)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.label_42 = QtGui.QLabel(self.page_cwf)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_42)
        self.page_connect_with_func_method = QtGui.QTextEdit(self.page_cwf)
        self.page_connect_with_func_method.setObjectName(_fromUtf8("page_connect_with_func_method"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.page_connect_with_func_method)
        self.label_44 = QtGui.QLabel(self.page_cwf)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_44)
        self.page_connect_with_func_args = QtGui.QLineEdit(self.page_cwf)
        self.page_connect_with_func_args.setObjectName(_fromUtf8("page_connect_with_func_args"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.FieldRole, self.page_connect_with_func_args)
        self.stackedWidget.addWidget(self.page_cwf)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(10)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Connector", None))
        self.label_6.setText(_translate("Dialog", "Connectivity", None))
        self.stackedWidget.setAccessibleName(_translate("Dialog", "test", None))
        self.page_defineown.setAccessibleName(_translate("Dialog", "New Connector", None))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#ff0000;\">this page is now not  available</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">problems to be solved:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 how to create a new widget and add it into a list?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2 how to synchronize this widget with other connector?</p></body></html>", None))
        self.page_cata.setAccessibleName(_translate("Dialog", "connect_all_to_all", None))
        self.label_2.setText(_translate("Dialog", "weights", None))
        self.label_48.setText(_translate("Dialog", "Uniform", None))
        self.label_46.setText(_translate("Dialog", "min", None))
        self.label_47.setText(_translate("Dialog", "max", None))
        self.label_3.setText(_translate("Dialog", "delays", None))
        self.label_49.setText(_translate("Dialog", "Uniform", None))
        self.label_50.setText(_translate("Dialog", "min", None))
        self.label_51.setText(_translate("Dialog", "max", None))
        self.label_4.setText(_translate("Dialog", "allow_self_connections", None))
        self.label_5.setText(_translate("Dialog", "force_multiple_weights", None))
        self.page_cd.setAccessibleName(_translate("Dialog", "connect_dog", None))
        self.label.setText(_translate("Dialog", "amp_pos", None))
        self.label_8.setText(_translate("Dialog", "amp_neg", None))
        self.label_7.setText(_translate("Dialog", "sigma_pos", None))
        self.label_9.setText(_translate("Dialog", "sigma_neg", None))
        self.label_11.setText(_translate("Dialog", "allow_self_connections", None))
        self.label_12.setText(_translate("Dialog", "limit", None))
        self.label_10.setText(_translate("Dialog", "delays", None))
        self.label_52.setText(_translate("Dialog", "Uniform", None))
        self.label_53.setText(_translate("Dialog", "min", None))
        self.label_54.setText(_translate("Dialog", "max", None))
        self.page_cfn_post.setAccessibleName(_translate("Dialog", "connect_fixed_number_post", None))
        self.label_14.setText(_translate("Dialog", "weights", None))
        self.label_58.setText(_translate("Dialog", "Uniform", None))
        self.label_59.setText(_translate("Dialog", "min", None))
        self.label_60.setText(_translate("Dialog", "max", None))
        self.label_15.setText(_translate("Dialog", "delays", None))
        self.label_55.setText(_translate("Dialog", "Uniform", None))
        self.label_56.setText(_translate("Dialog", "min", None))
        self.label_57.setText(_translate("Dialog", "max", None))
        self.label_13.setText(_translate("Dialog", "number", None))
        self.label_16.setText(_translate("Dialog", "allow_self_connections ", None))
        self.label_17.setText(_translate("Dialog", "force_multiple_weights", None))
        self.page_cfn_pre.setAccessibleName(_translate("Dialog", "connect_fixed_number_pre", None))
        self.label_20.setText(_translate("Dialog", "weights", None))
        self.label_61.setText(_translate("Dialog", "Uniform", None))
        self.label_62.setText(_translate("Dialog", "min", None))
        self.label_63.setText(_translate("Dialog", "max", None))
        self.label_19.setText(_translate("Dialog", "delays", None))
        self.label_64.setText(_translate("Dialog", "Uniform", None))
        self.label_65.setText(_translate("Dialog", "min", None))
        self.label_66.setText(_translate("Dialog", "max", None))
        self.label_22.setText(_translate("Dialog", "number", None))
        self.label_18.setText(_translate("Dialog", "allow_self_connections ", None))
        self.label_21.setText(_translate("Dialog", "force_multiple_weights", None))
        self.page_cfp.setAccessibleName(_translate("Dialog", "connect_fixed_probability", None))
        self.label_24.setText(_translate("Dialog", "weights", None))
        self.label_67.setText(_translate("Dialog", "Uniform", None))
        self.label_68.setText(_translate("Dialog", "min", None))
        self.label_69.setText(_translate("Dialog", "max", None))
        self.label_23.setText(_translate("Dialog", "delays", None))
        self.label_70.setText(_translate("Dialog", "Uniform", None))
        self.label_71.setText(_translate("Dialog", "min", None))
        self.label_72.setText(_translate("Dialog", "max", None))
        self.label_27.setText(_translate("Dialog", "probability", None))
        self.label_26.setText(_translate("Dialog", "allow_self_connections ", None))
        self.label_25.setText(_translate("Dialog", "force_multiple_weights", None))
        self.label_73.setText(_translate("Dialog", "%", None))
        self.page_cff.setAccessibleName(_translate("Dialog", "connect_from_file", None))
        self.cff_openfile.setText(_translate("Dialog", "open file", None))
        self.label_43.setText(_translate("Dialog", "FileName", None))
        self.label_45.setText(_translate("Dialog", "Path", None))
        self.page_cfm.setAccessibleName(_translate("Dialog", "connect_from_matrix", None))
        self.label_28.setText(_translate("Dialog", "weights", None))
        self.label_29.setText(_translate("Dialog", "delays", None))
        self.label_30.setText(_translate("Dialog", "pre_post", None))
        self.page_cfs.setAccessibleName(_translate("Dialog", "connect_from_sparse", None))
        self.label_31.setText(_translate("Dialog", "weights", None))
        self.label_32.setText(_translate("Dialog", "delays", None))
        self.page_cg.setAccessibleName(_translate("Dialog", "connect_gaussian", None))
        self.label_33.setText(_translate("Dialog", "amp", None))
        self.label_35.setText(_translate("Dialog", "delays", None))
        self.label_36.setText(_translate("Dialog", "limit", None))
        self.label_74.setText(_translate("Dialog", "Uniform", None))
        self.label_75.setText(_translate("Dialog", "min", None))
        self.label_76.setText(_translate("Dialog", "max", None))
        self.label_34.setText(_translate("Dialog", "sigma", None))
        self.label_37.setText(_translate("Dialog", "allow_self_connections", None))
        self.page_coto.setAccessibleName(_translate("Dialog", "connect_one_to_one", None))
        self.label_41.setText(_translate("Dialog", "force_multiple_weights", None))
        self.label_39.setText(_translate("Dialog", "delays", None))
        self.label_77.setText(_translate("Dialog", "Uniform", None))
        self.label_78.setText(_translate("Dialog", "min", None))
        self.label_79.setText(_translate("Dialog", "max", None))
        self.label_40.setText(_translate("Dialog", "shift", None))
        self.label_80.setText(_translate("Dialog", "Uniform", None))
        self.label_81.setText(_translate("Dialog", "min", None))
        self.label_82.setText(_translate("Dialog", "max", None))
        self.label_38.setText(_translate("Dialog", "weights", None))
        self.page_cwf.setAccessibleName(_translate("Dialog", "connect_with_func", None))
        self.label_42.setText(_translate("Dialog", "method", None))
        self.label_44.setText(_translate("Dialog", "args", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

