# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Connector_Definition.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(246, 331)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.comboBox_connectivity = QtGui.QComboBox(Dialog)
        self.comboBox_connectivity.setObjectName(_fromUtf8("comboBox_connectivity"))
        self.horizontalLayout_2.addWidget(self.comboBox_connectivity)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.stackedWidget = QtGui.QStackedWidget(Dialog)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page_defineown = QtGui.QWidget()
        self.page_defineown.setObjectName(_fromUtf8("page_defineown"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_defineown)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.textBrowser = QtGui.QTextBrowser(self.page_defineown)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_3.addWidget(self.textBrowser)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.stackedWidget.addWidget(self.page_defineown)
        self.page_connect_all_to_all = QtGui.QWidget()
        self.page_connect_all_to_all.setObjectName(_fromUtf8("page_connect_all_to_all"))
        self.formLayout_2 = QtGui.QFormLayout(self.page_connect_all_to_all)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.page_connect_all_to_all)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.page_connect_all_to_all)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.page_connect_all_to_all)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.connect_all_to_all_asc = QtGui.QComboBox(self.page_connect_all_to_all)
        self.connect_all_to_all_asc.setObjectName(_fromUtf8("connect_all_to_all_asc"))
        self.connect_all_to_all_asc.addItem(_fromUtf8(""))
        self.connect_all_to_all_asc.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.connect_all_to_all_asc)
        self.label_5 = QtGui.QLabel(self.page_connect_all_to_all)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.connect_all_to_all_fmw = QtGui.QComboBox(self.page_connect_all_to_all)
        self.connect_all_to_all_fmw.setObjectName(_fromUtf8("connect_all_to_all_fmw"))
        self.connect_all_to_all_fmw.addItem(_fromUtf8(""))
        self.connect_all_to_all_fmw.addItem(_fromUtf8(""))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.connect_all_to_all_fmw)
        self.connect_all_to_all_weight = QtGui.QLineEdit(self.page_connect_all_to_all)
        self.connect_all_to_all_weight.setObjectName(_fromUtf8("connect_all_to_all_weight"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.connect_all_to_all_weight)
        self.connect_all_to_all_delay = QtGui.QLineEdit(self.page_connect_all_to_all)
        self.connect_all_to_all_delay.setObjectName(_fromUtf8("connect_all_to_all_delay"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.connect_all_to_all_delay)
        self.stackedWidget.addWidget(self.page_connect_all_to_all)
        self.page_connect_dog = QtGui.QWidget()
        self.page_connect_dog.setObjectName(_fromUtf8("page_connect_dog"))
        self.formLayout = QtGui.QFormLayout(self.page_connect_dog)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.page_connect_dog)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.page_connect_dog_amp_pos = QtGui.QDoubleSpinBox(self.page_connect_dog)
        self.page_connect_dog_amp_pos.setObjectName(_fromUtf8("page_connect_dog_amp_pos"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.page_connect_dog_amp_pos)
        self.label_7 = QtGui.QLabel(self.page_connect_dog)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.page_connect_dog_sigma_pos = QtGui.QDoubleSpinBox(self.page_connect_dog)
        self.page_connect_dog_sigma_pos.setObjectName(_fromUtf8("page_connect_dog_sigma_pos"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.page_connect_dog_sigma_pos)
        self.label_8 = QtGui.QLabel(self.page_connect_dog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.page_connect_dog_amp_neg = QtGui.QDoubleSpinBox(self.page_connect_dog)
        self.page_connect_dog_amp_neg.setObjectName(_fromUtf8("page_connect_dog_amp_neg"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.page_connect_dog_amp_neg)
        self.label_9 = QtGui.QLabel(self.page_connect_dog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.page_connect_dog_sigma_neg = QtGui.QDoubleSpinBox(self.page_connect_dog)
        self.page_connect_dog_sigma_neg.setObjectName(_fromUtf8("page_connect_dog_sigma_neg"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.page_connect_dog_sigma_neg)
        self.label_10 = QtGui.QLabel(self.page_connect_dog)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_12 = QtGui.QLabel(self.page_connect_dog)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_12)
        self.page_connect_dog_limit = QtGui.QDoubleSpinBox(self.page_connect_dog)
        self.page_connect_dog_limit.setProperty("value", 0.01)
        self.page_connect_dog_limit.setObjectName(_fromUtf8("page_connect_dog_limit"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.page_connect_dog_limit)
        self.label_11 = QtGui.QLabel(self.page_connect_dog)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_11)
        self.page_connect_dog_asc = QtGui.QComboBox(self.page_connect_dog)
        self.page_connect_dog_asc.setObjectName(_fromUtf8("page_connect_dog_asc"))
        self.page_connect_dog_asc.addItem(_fromUtf8(""))
        self.page_connect_dog_asc.addItem(_fromUtf8(""))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.page_connect_dog_asc)
        self.page_connect_dog_delays = QtGui.QLineEdit(self.page_connect_dog)
        self.page_connect_dog_delays.setObjectName(_fromUtf8("page_connect_dog_delays"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.page_connect_dog_delays)
        self.stackedWidget.addWidget(self.page_connect_dog)
        self.page_connect_fixed_number_post = QtGui.QWidget()
        self.page_connect_fixed_number_post.setObjectName(_fromUtf8("page_connect_fixed_number_post"))
        self.formLayout_3 = QtGui.QFormLayout(self.page_connect_fixed_number_post)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_13 = QtGui.QLabel(self.page_connect_fixed_number_post)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_13)
        self.page_connect_fixed_number_post_number = QtGui.QSpinBox(self.page_connect_fixed_number_post)
        self.page_connect_fixed_number_post_number.setObjectName(_fromUtf8("page_connect_fixed_number_post_number"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_number_post_number)
        self.label_14 = QtGui.QLabel(self.page_connect_fixed_number_post)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_14)
        self.page_connect_fixed_number_post_weights = QtGui.QLineEdit(self.page_connect_fixed_number_post)
        self.page_connect_fixed_number_post_weights.setObjectName(_fromUtf8("page_connect_fixed_number_post_weights"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_number_post_weights)
        self.label_15 = QtGui.QLabel(self.page_connect_fixed_number_post)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_15)
        self.page_connect_fixed_number_post_delays = QtGui.QLineEdit(self.page_connect_fixed_number_post)
        self.page_connect_fixed_number_post_delays.setObjectName(_fromUtf8("page_connect_fixed_number_post_delays"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_number_post_delays)
        self.label_16 = QtGui.QLabel(self.page_connect_fixed_number_post)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_16)
        self.page_connect_fixed_number_post_asc = QtGui.QComboBox(self.page_connect_fixed_number_post)
        self.page_connect_fixed_number_post_asc.setObjectName(_fromUtf8("page_connect_fixed_number_post_asc"))
        self.page_connect_fixed_number_post_asc.addItem(_fromUtf8(""))
        self.page_connect_fixed_number_post_asc.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_number_post_asc)
        self.label_17 = QtGui.QLabel(self.page_connect_fixed_number_post)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_17)
        self.page_connect_fixed_number_post_fmw = QtGui.QComboBox(self.page_connect_fixed_number_post)
        self.page_connect_fixed_number_post_fmw.setObjectName(_fromUtf8("page_connect_fixed_number_post_fmw"))
        self.page_connect_fixed_number_post_fmw.addItem(_fromUtf8(""))
        self.page_connect_fixed_number_post_fmw.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_number_post_fmw)
        self.stackedWidget.addWidget(self.page_connect_fixed_number_post)
        self.page_connect_fixed_number_pre = QtGui.QWidget()
        self.page_connect_fixed_number_pre.setObjectName(_fromUtf8("page_connect_fixed_number_pre"))
        self.formLayout_4 = QtGui.QFormLayout(self.page_connect_fixed_number_pre)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_18 = QtGui.QLabel(self.page_connect_fixed_number_pre)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_18)
        self.page_connect_fixed_number_pre_number = QtGui.QSpinBox(self.page_connect_fixed_number_pre)
        self.page_connect_fixed_number_pre_number.setObjectName(_fromUtf8("page_connect_fixed_number_pre_number"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_number_pre_number)
        self.label_21 = QtGui.QLabel(self.page_connect_fixed_number_pre)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_21)
        self.page_connect_fixed_number_pre_weights = QtGui.QLineEdit(self.page_connect_fixed_number_pre)
        self.page_connect_fixed_number_pre_weights.setObjectName(_fromUtf8("page_connect_fixed_number_pre_weights"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_number_pre_weights)
        self.label_20 = QtGui.QLabel(self.page_connect_fixed_number_pre)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_20)
        self.page_connect_fixed_number_pre_delays = QtGui.QLineEdit(self.page_connect_fixed_number_pre)
        self.page_connect_fixed_number_pre_delays.setObjectName(_fromUtf8("page_connect_fixed_number_pre_delays"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_number_pre_delays)
        self.label_19 = QtGui.QLabel(self.page_connect_fixed_number_pre)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_19)
        self.page_connect_fixed_number_pre_asc = QtGui.QComboBox(self.page_connect_fixed_number_pre)
        self.page_connect_fixed_number_pre_asc.setObjectName(_fromUtf8("page_connect_fixed_number_pre_asc"))
        self.page_connect_fixed_number_pre_asc.addItem(_fromUtf8(""))
        self.page_connect_fixed_number_pre_asc.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_number_pre_asc)
        self.label_22 = QtGui.QLabel(self.page_connect_fixed_number_pre)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_22)
        self.page_connect_fixed_number_pre_fmw = QtGui.QComboBox(self.page_connect_fixed_number_pre)
        self.page_connect_fixed_number_pre_fmw.setObjectName(_fromUtf8("page_connect_fixed_number_pre_fmw"))
        self.page_connect_fixed_number_pre_fmw.addItem(_fromUtf8(""))
        self.page_connect_fixed_number_pre_fmw.addItem(_fromUtf8(""))
        self.formLayout_4.setWidget(4, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_number_pre_fmw)
        self.stackedWidget.addWidget(self.page_connect_fixed_number_pre)
        self.page_connect_fixed_probability = QtGui.QWidget()
        self.page_connect_fixed_probability.setObjectName(_fromUtf8("page_connect_fixed_probability"))
        self.formLayout_5 = QtGui.QFormLayout(self.page_connect_fixed_probability)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.label_23 = QtGui.QLabel(self.page_connect_fixed_probability)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_23)
        self.page_connect_fixed_probability_probability = QtGui.QLineEdit(self.page_connect_fixed_probability)
        self.page_connect_fixed_probability_probability.setObjectName(_fromUtf8("page_connect_fixed_probability_probability"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_probability_probability)
        self.label_24 = QtGui.QLabel(self.page_connect_fixed_probability)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_24)
        self.page_connect_fixed_probability_weights = QtGui.QLineEdit(self.page_connect_fixed_probability)
        self.page_connect_fixed_probability_weights.setObjectName(_fromUtf8("page_connect_fixed_probability_weights"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_probability_weights)
        self.label_25 = QtGui.QLabel(self.page_connect_fixed_probability)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_25)
        self.page_connect_fixed_probability_delays = QtGui.QLineEdit(self.page_connect_fixed_probability)
        self.page_connect_fixed_probability_delays.setObjectName(_fromUtf8("page_connect_fixed_probability_delays"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_probability_delays)
        self.label_26 = QtGui.QLabel(self.page_connect_fixed_probability)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_26)
        self.page_connect_fixed_probability_asc = QtGui.QComboBox(self.page_connect_fixed_probability)
        self.page_connect_fixed_probability_asc.setObjectName(_fromUtf8("page_connect_fixed_probability_asc"))
        self.page_connect_fixed_probability_asc.addItem(_fromUtf8(""))
        self.page_connect_fixed_probability_asc.addItem(_fromUtf8(""))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_probability_asc)
        self.label_27 = QtGui.QLabel(self.page_connect_fixed_probability)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_27)
        self.page_connect_fixed_probability_fmw = QtGui.QComboBox(self.page_connect_fixed_probability)
        self.page_connect_fixed_probability_fmw.setObjectName(_fromUtf8("page_connect_fixed_probability_fmw"))
        self.page_connect_fixed_probability_fmw.addItem(_fromUtf8(""))
        self.page_connect_fixed_probability_fmw.addItem(_fromUtf8(""))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.page_connect_fixed_probability_fmw)
        self.stackedWidget.addWidget(self.page_connect_fixed_probability)
        self.page_connect_from_file = QtGui.QWidget()
        self.page_connect_from_file.setObjectName(_fromUtf8("page_connect_from_file"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.page_connect_from_file)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButton_openfile = QtGui.QPushButton(self.page_connect_from_file)
        self.pushButton_openfile.setObjectName(_fromUtf8("pushButton_openfile"))
        self.horizontalLayout_3.addWidget(self.pushButton_openfile)
        self.stackedWidget.addWidget(self.page_connect_from_file)
        self.page_connect_from_matrix = QtGui.QWidget()
        self.page_connect_from_matrix.setObjectName(_fromUtf8("page_connect_from_matrix"))
        self.formLayout_6 = QtGui.QFormLayout(self.page_connect_from_matrix)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_28 = QtGui.QLabel(self.page_connect_from_matrix)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_28)
        self.page_connect_from_matrix_weights = QtGui.QPlainTextEdit(self.page_connect_from_matrix)
        self.page_connect_from_matrix_weights.setObjectName(_fromUtf8("page_connect_from_matrix_weights"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.page_connect_from_matrix_weights)
        self.label_29 = QtGui.QLabel(self.page_connect_from_matrix)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_29)
        self.page_connect_from_matrix_delays = QtGui.QTextEdit(self.page_connect_from_matrix)
        self.page_connect_from_matrix_delays.setObjectName(_fromUtf8("page_connect_from_matrix_delays"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.page_connect_from_matrix_delays)
        self.label_30 = QtGui.QLabel(self.page_connect_from_matrix)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_30)
        self.page_connect_from_matrix_pre_post = QtGui.QComboBox(self.page_connect_from_matrix)
        self.page_connect_from_matrix_pre_post.setObjectName(_fromUtf8("page_connect_from_matrix_pre_post"))
        self.page_connect_from_matrix_pre_post.addItem(_fromUtf8(""))
        self.page_connect_from_matrix_pre_post.addItem(_fromUtf8(""))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.page_connect_from_matrix_pre_post)
        self.stackedWidget.addWidget(self.page_connect_from_matrix)
        self.page_connect_from_sparse = QtGui.QWidget()
        self.page_connect_from_sparse.setObjectName(_fromUtf8("page_connect_from_sparse"))
        self.formLayout_7 = QtGui.QFormLayout(self.page_connect_from_sparse)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.label_31 = QtGui.QLabel(self.page_connect_from_sparse)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_31)
        self.page_connect_from_sparse_weights = QtGui.QPlainTextEdit(self.page_connect_from_sparse)
        self.page_connect_from_sparse_weights.setObjectName(_fromUtf8("page_connect_from_sparse_weights"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.page_connect_from_sparse_weights)
        self.label_32 = QtGui.QLabel(self.page_connect_from_sparse)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_32)
        self.page_connect_from_sparse_delays = QtGui.QLineEdit(self.page_connect_from_sparse)
        self.page_connect_from_sparse_delays.setObjectName(_fromUtf8("page_connect_from_sparse_delays"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.page_connect_from_sparse_delays)
        self.stackedWidget.addWidget(self.page_connect_from_sparse)
        self.page_connect_gaussian = QtGui.QWidget()
        self.page_connect_gaussian.setObjectName(_fromUtf8("page_connect_gaussian"))
        self.formLayout_8 = QtGui.QFormLayout(self.page_connect_gaussian)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.label_33 = QtGui.QLabel(self.page_connect_gaussian)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_33)
        self.page_connect_gaussian_amp = QtGui.QLineEdit(self.page_connect_gaussian)
        self.page_connect_gaussian_amp.setObjectName(_fromUtf8("page_connect_gaussian_amp"))
        self.formLayout_8.setWidget(0, QtGui.QFormLayout.FieldRole, self.page_connect_gaussian_amp)
        self.label_34 = QtGui.QLabel(self.page_connect_gaussian)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_34)
        self.page_connect_gaussian_sigma = QtGui.QLineEdit(self.page_connect_gaussian)
        self.page_connect_gaussian_sigma.setObjectName(_fromUtf8("page_connect_gaussian_sigma"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.page_connect_gaussian_sigma)
        self.label_35 = QtGui.QLabel(self.page_connect_gaussian)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_35)
        self.page_connect_gaussian_delays = QtGui.QLineEdit(self.page_connect_gaussian)
        self.page_connect_gaussian_delays.setObjectName(_fromUtf8("page_connect_gaussian_delays"))
        self.formLayout_8.setWidget(2, QtGui.QFormLayout.FieldRole, self.page_connect_gaussian_delays)
        self.label_36 = QtGui.QLabel(self.page_connect_gaussian)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_36)
        self.page_connect_gaussian_limit = QtGui.QLineEdit(self.page_connect_gaussian)
        self.page_connect_gaussian_limit.setObjectName(_fromUtf8("page_connect_gaussian_limit"))
        self.formLayout_8.setWidget(3, QtGui.QFormLayout.FieldRole, self.page_connect_gaussian_limit)
        self.label_37 = QtGui.QLabel(self.page_connect_gaussian)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.formLayout_8.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_37)
        self.page_connect_gaussian_asc = QtGui.QComboBox(self.page_connect_gaussian)
        self.page_connect_gaussian_asc.setObjectName(_fromUtf8("page_connect_gaussian_asc"))
        self.page_connect_gaussian_asc.addItem(_fromUtf8(""))
        self.page_connect_gaussian_asc.addItem(_fromUtf8(""))
        self.formLayout_8.setWidget(4, QtGui.QFormLayout.FieldRole, self.page_connect_gaussian_asc)
        self.stackedWidget.addWidget(self.page_connect_gaussian)
        self.page_connect_one_to_one = QtGui.QWidget()
        self.page_connect_one_to_one.setObjectName(_fromUtf8("page_connect_one_to_one"))
        self.formLayout_9 = QtGui.QFormLayout(self.page_connect_one_to_one)
        self.formLayout_9.setObjectName(_fromUtf8("formLayout_9"))
        self.label_38 = QtGui.QLabel(self.page_connect_one_to_one)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_38)
        self.page_connect_one_to_one_weights = QtGui.QLineEdit(self.page_connect_one_to_one)
        self.page_connect_one_to_one_weights.setObjectName(_fromUtf8("page_connect_one_to_one_weights"))
        self.formLayout_9.setWidget(0, QtGui.QFormLayout.FieldRole, self.page_connect_one_to_one_weights)
        self.label_39 = QtGui.QLabel(self.page_connect_one_to_one)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_39)
        self.delays = QtGui.QLineEdit(self.page_connect_one_to_one)
        self.delays.setObjectName(_fromUtf8("delays"))
        self.formLayout_9.setWidget(1, QtGui.QFormLayout.FieldRole, self.delays)
        self.label_40 = QtGui.QLabel(self.page_connect_one_to_one)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_40)
        self.page_connect_one_to_one_shift = QtGui.QComboBox(self.page_connect_one_to_one)
        self.page_connect_one_to_one_shift.setObjectName(_fromUtf8("page_connect_one_to_one_shift"))
        self.page_connect_one_to_one_shift.addItem(_fromUtf8(""))
        self.page_connect_one_to_one_shift.addItem(_fromUtf8(""))
        self.formLayout_9.setWidget(2, QtGui.QFormLayout.FieldRole, self.page_connect_one_to_one_shift)
        self.label_41 = QtGui.QLabel(self.page_connect_one_to_one)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.formLayout_9.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_41)
        self.page_connect_one_to_one_fmw = QtGui.QComboBox(self.page_connect_one_to_one)
        self.page_connect_one_to_one_fmw.setObjectName(_fromUtf8("page_connect_one_to_one_fmw"))
        self.page_connect_one_to_one_fmw.addItem(_fromUtf8(""))
        self.page_connect_one_to_one_fmw.addItem(_fromUtf8(""))
        self.formLayout_9.setWidget(3, QtGui.QFormLayout.FieldRole, self.page_connect_one_to_one_fmw)
        self.stackedWidget.addWidget(self.page_connect_one_to_one)
        self.page_connect_with_func = QtGui.QWidget()
        self.page_connect_with_func.setObjectName(_fromUtf8("page_connect_with_func"))
        self.formLayout_10 = QtGui.QFormLayout(self.page_connect_with_func)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.label_42 = QtGui.QLabel(self.page_connect_with_func)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_42)
        self.page_connect_with_func_method = QtGui.QTextEdit(self.page_connect_with_func)
        self.page_connect_with_func_method.setObjectName(_fromUtf8("page_connect_with_func_method"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.FieldRole, self.page_connect_with_func_method)
        self.label_44 = QtGui.QLabel(self.page_connect_with_func)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_44)
        self.page_connect_with_func_args = QtGui.QLineEdit(self.page_connect_with_func)
        self.page_connect_with_func_args.setObjectName(_fromUtf8("page_connect_with_func_args"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.FieldRole, self.page_connect_with_func_args)
        self.stackedWidget.addWidget(self.page_connect_with_func)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Connector", None))
        self.label_6.setText(_translate("Dialog", "Connectivity", None))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1 how to create a new widget and add it into a list?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2 how to synchronize this list with other connector</p></body></html>", None))
        self.label_2.setText(_translate("Dialog", "weights", None))
        self.label_3.setText(_translate("Dialog", "delays", None))
        self.label_4.setText(_translate("Dialog", "allow_self_connections", None))
        self.connect_all_to_all_asc.setItemText(0, _translate("Dialog", "False", None))
        self.connect_all_to_all_asc.setItemText(1, _translate("Dialog", "True", None))
        self.label_5.setText(_translate("Dialog", "force_multiple_weights", None))
        self.connect_all_to_all_fmw.setItemText(0, _translate("Dialog", "False", None))
        self.connect_all_to_all_fmw.setItemText(1, _translate("Dialog", "True", None))
        self.label.setText(_translate("Dialog", "amp_pos", None))
        self.label_7.setText(_translate("Dialog", "sigma_pos", None))
        self.label_8.setText(_translate("Dialog", "amp_neg", None))
        self.label_9.setText(_translate("Dialog", "sigma_neg", None))
        self.label_10.setText(_translate("Dialog", "delays", None))
        self.label_12.setText(_translate("Dialog", "limit", None))
        self.label_11.setText(_translate("Dialog", "allow_self_connections", None))
        self.page_connect_dog_asc.setItemText(0, _translate("Dialog", "False", None))
        self.page_connect_dog_asc.setItemText(1, _translate("Dialog", "True", None))
        self.label_13.setText(_translate("Dialog", "number", None))
        self.label_14.setText(_translate("Dialog", "weights", None))
        self.label_15.setText(_translate("Dialog", "delays", None))
        self.label_16.setText(_translate("Dialog", "allow_self_connections ", None))
        self.page_connect_fixed_number_post_asc.setItemText(0, _translate("Dialog", "False", None))
        self.page_connect_fixed_number_post_asc.setItemText(1, _translate("Dialog", "True", None))
        self.label_17.setText(_translate("Dialog", "force_multiple_weights", None))
        self.page_connect_fixed_number_post_fmw.setItemText(0, _translate("Dialog", "False", None))
        self.page_connect_fixed_number_post_fmw.setItemText(1, _translate("Dialog", "True", None))
        self.label_18.setText(_translate("Dialog", "number", None))
        self.label_21.setText(_translate("Dialog", "weights", None))
        self.label_20.setText(_translate("Dialog", "delays", None))
        self.label_19.setText(_translate("Dialog", "allow_self_connections ", None))
        self.page_connect_fixed_number_pre_asc.setItemText(0, _translate("Dialog", "False", None))
        self.page_connect_fixed_number_pre_asc.setItemText(1, _translate("Dialog", "True", None))
        self.label_22.setText(_translate("Dialog", "force_multiple_weights", None))
        self.page_connect_fixed_number_pre_fmw.setItemText(0, _translate("Dialog", "False", None))
        self.page_connect_fixed_number_pre_fmw.setItemText(1, _translate("Dialog", "True", None))
        self.label_23.setText(_translate("Dialog", "probability", None))
        self.label_24.setText(_translate("Dialog", "weights", None))
        self.label_25.setText(_translate("Dialog", "delays", None))
        self.label_26.setText(_translate("Dialog", "allow_self_connections ", None))
        self.page_connect_fixed_probability_asc.setItemText(0, _translate("Dialog", "False", None))
        self.page_connect_fixed_probability_asc.setItemText(1, _translate("Dialog", "True", None))
        self.label_27.setText(_translate("Dialog", "force_multiple_weights", None))
        self.page_connect_fixed_probability_fmw.setItemText(0, _translate("Dialog", "False", None))
        self.page_connect_fixed_probability_fmw.setItemText(1, _translate("Dialog", "True", None))
        self.pushButton_openfile.setText(_translate("Dialog", "open file", None))
        self.label_28.setText(_translate("Dialog", "weights", None))
        self.label_29.setText(_translate("Dialog", "delays", None))
        self.label_30.setText(_translate("Dialog", "pre_post", None))
        self.page_connect_from_matrix_pre_post.setItemText(0, _translate("Dialog", "False", None))
        self.page_connect_from_matrix_pre_post.setItemText(1, _translate("Dialog", "True", None))
        self.label_31.setText(_translate("Dialog", "weights", None))
        self.label_32.setText(_translate("Dialog", "delays", None))
        self.label_33.setText(_translate("Dialog", "amp", None))
        self.label_34.setText(_translate("Dialog", "sigma", None))
        self.label_35.setText(_translate("Dialog", "delays", None))
        self.label_36.setText(_translate("Dialog", "limit", None))
        self.label_37.setText(_translate("Dialog", "allow_self_connections", None))
        self.page_connect_gaussian_asc.setItemText(0, _translate("Dialog", "False", None))
        self.page_connect_gaussian_asc.setItemText(1, _translate("Dialog", "True", None))
        self.label_38.setText(_translate("Dialog", "weights", None))
        self.label_39.setText(_translate("Dialog", "delays", None))
        self.label_40.setText(_translate("Dialog", "shift", None))
        self.page_connect_one_to_one_shift.setItemText(0, _translate("Dialog", "False", None))
        self.page_connect_one_to_one_shift.setItemText(1, _translate("Dialog", "True", None))
        self.label_41.setText(_translate("Dialog", "force_multiple_weights", None))
        self.page_connect_one_to_one_fmw.setItemText(0, _translate("Dialog", "False", None))
        self.page_connect_one_to_one_fmw.setItemText(1, _translate("Dialog", "True", None))
        self.label_42.setText(_translate("Dialog", "method", None))
        self.label_44.setText(_translate("Dialog", "args", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

